[package]
name = "catalog"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.6"
domain = { version = "0.1.0", path = "../domain" }
infer = "0.22.0"
platform = { version = "0.1.0", path = "../platform" }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
uuid = { version = "1.24.0", features = ["v7"] }
